// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ublewseczozfewhpctum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVibGV3c2Vjem96ZmV3aHBjdHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjcxNDYsImV4cCI6MjA3MTAwMzE0Nn0._aMSIi7QfAyjSmrH26bppaQ6r9RX-JPhoXPHsX5r2ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});